export default [
  {
    id: 563949699,
    node_id: "R_kgDOIZ0wgw",
    name: "xio",
    full_name: "Zuma206/xio",
    private: false,
    owner: {
      login: "Zuma206",
      id: 62074989,
      node_id: "MDQ6VXNlcjYyMDc0OTg5",
      avatar_url: "https://avatars.githubusercontent.com/u/62074989?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Zuma206",
      html_url: "https://github.com/Zuma206",
      followers_url: "https://api.github.com/users/Zuma206/followers",
      following_url:
        "https://api.github.com/users/Zuma206/following{/other_user}",
      gists_url: "https://api.github.com/users/Zuma206/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/Zuma206/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Zuma206/subscriptions",
      organizations_url: "https://api.github.com/users/Zuma206/orgs",
      repos_url: "https://api.github.com/users/Zuma206/repos",
      events_url: "https://api.github.com/users/Zuma206/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/Zuma206/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/Zuma206/xio",
    description: "XIO React client",
    fork: false,
    url: "https://api.github.com/repos/Zuma206/xio",
    forks_url: "https://api.github.com/repos/Zuma206/xio/forks",
    keys_url: "https://api.github.com/repos/Zuma206/xio/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/Zuma206/xio/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/Zuma206/xio/teams",
    hooks_url: "https://api.github.com/repos/Zuma206/xio/hooks",
    issue_events_url:
      "https://api.github.com/repos/Zuma206/xio/issues/events{/number}",
    events_url: "https://api.github.com/repos/Zuma206/xio/events",
    assignees_url: "https://api.github.com/repos/Zuma206/xio/assignees{/user}",
    branches_url: "https://api.github.com/repos/Zuma206/xio/branches{/branch}",
    tags_url: "https://api.github.com/repos/Zuma206/xio/tags",
    blobs_url: "https://api.github.com/repos/Zuma206/xio/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/Zuma206/xio/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/Zuma206/xio/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/Zuma206/xio/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/Zuma206/xio/statuses/{sha}",
    languages_url: "https://api.github.com/repos/Zuma206/xio/languages",
    stargazers_url: "https://api.github.com/repos/Zuma206/xio/stargazers",
    contributors_url: "https://api.github.com/repos/Zuma206/xio/contributors",
    subscribers_url: "https://api.github.com/repos/Zuma206/xio/subscribers",
    subscription_url: "https://api.github.com/repos/Zuma206/xio/subscription",
    commits_url: "https://api.github.com/repos/Zuma206/xio/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/Zuma206/xio/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/Zuma206/xio/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/Zuma206/xio/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/Zuma206/xio/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/Zuma206/xio/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/Zuma206/xio/merges",
    archive_url:
      "https://api.github.com/repos/Zuma206/xio/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/Zuma206/xio/downloads",
    issues_url: "https://api.github.com/repos/Zuma206/xio/issues{/number}",
    pulls_url: "https://api.github.com/repos/Zuma206/xio/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/Zuma206/xio/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/Zuma206/xio/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/Zuma206/xio/labels{/name}",
    releases_url: "https://api.github.com/repos/Zuma206/xio/releases{/id}",
    deployments_url: "https://api.github.com/repos/Zuma206/xio/deployments",
    created_at: "2022-11-09T17:13:04Z",
    updated_at: "2023-08-16T16:57:35Z",
    pushed_at: "2023-03-09T16:53:26Z",
    git_url: "git://github.com/Zuma206/xio.git",
    ssh_url: "git@github.com:Zuma206/xio.git",
    clone_url: "https://github.com/Zuma206/xio.git",
    svn_url: "https://github.com/Zuma206/xio",
    homepage: "https://xio.zuma.eu.org",
    size: 486,
    stargazers_count: 0,
    watchers_count: 0,
    language: "TypeScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ["chat", "firebase", "react", "site", "spa", "vite"],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: "main",
  },
  {
    id: 566062117,
    node_id: "R_kgDOIb1sJQ",
    name: "xio-server",
    full_name: "Zuma206/xio-server",
    private: false,
    owner: {
      login: "Zuma206",
      id: 62074989,
      node_id: "MDQ6VXNlcjYyMDc0OTg5",
      avatar_url: "https://avatars.githubusercontent.com/u/62074989?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Zuma206",
      html_url: "https://github.com/Zuma206",
      followers_url: "https://api.github.com/users/Zuma206/followers",
      following_url:
        "https://api.github.com/users/Zuma206/following{/other_user}",
      gists_url: "https://api.github.com/users/Zuma206/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/Zuma206/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Zuma206/subscriptions",
      organizations_url: "https://api.github.com/users/Zuma206/orgs",
      repos_url: "https://api.github.com/users/Zuma206/repos",
      events_url: "https://api.github.com/users/Zuma206/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/Zuma206/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/Zuma206/xio-server",
    description: "XIO's Express based server",
    fork: false,
    url: "https://api.github.com/repos/Zuma206/xio-server",
    forks_url: "https://api.github.com/repos/Zuma206/xio-server/forks",
    keys_url: "https://api.github.com/repos/Zuma206/xio-server/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/Zuma206/xio-server/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/Zuma206/xio-server/teams",
    hooks_url: "https://api.github.com/repos/Zuma206/xio-server/hooks",
    issue_events_url:
      "https://api.github.com/repos/Zuma206/xio-server/issues/events{/number}",
    events_url: "https://api.github.com/repos/Zuma206/xio-server/events",
    assignees_url:
      "https://api.github.com/repos/Zuma206/xio-server/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/Zuma206/xio-server/branches{/branch}",
    tags_url: "https://api.github.com/repos/Zuma206/xio-server/tags",
    blobs_url:
      "https://api.github.com/repos/Zuma206/xio-server/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/Zuma206/xio-server/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/Zuma206/xio-server/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/Zuma206/xio-server/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/Zuma206/xio-server/statuses/{sha}",
    languages_url: "https://api.github.com/repos/Zuma206/xio-server/languages",
    stargazers_url:
      "https://api.github.com/repos/Zuma206/xio-server/stargazers",
    contributors_url:
      "https://api.github.com/repos/Zuma206/xio-server/contributors",
    subscribers_url:
      "https://api.github.com/repos/Zuma206/xio-server/subscribers",
    subscription_url:
      "https://api.github.com/repos/Zuma206/xio-server/subscription",
    commits_url:
      "https://api.github.com/repos/Zuma206/xio-server/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/Zuma206/xio-server/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/Zuma206/xio-server/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/Zuma206/xio-server/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/Zuma206/xio-server/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/Zuma206/xio-server/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/Zuma206/xio-server/merges",
    archive_url:
      "https://api.github.com/repos/Zuma206/xio-server/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/Zuma206/xio-server/downloads",
    issues_url:
      "https://api.github.com/repos/Zuma206/xio-server/issues{/number}",
    pulls_url: "https://api.github.com/repos/Zuma206/xio-server/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/Zuma206/xio-server/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/Zuma206/xio-server/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/Zuma206/xio-server/labels{/name}",
    releases_url:
      "https://api.github.com/repos/Zuma206/xio-server/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/Zuma206/xio-server/deployments",
    created_at: "2022-11-14T22:18:57Z",
    updated_at: "2023-08-16T16:57:52Z",
    pushed_at: "2023-03-23T19:33:27Z",
    git_url: "git://github.com/Zuma206/xio-server.git",
    ssh_url: "git@github.com:Zuma206/xio-server.git",
    clone_url: "https://github.com/Zuma206/xio-server.git",
    svn_url: "https://github.com/Zuma206/xio-server",
    homepage: "https://api.xio.zuma.eu.org",
    size: 446,
    stargazers_count: 1,
    watchers_count: 1,
    language: "TypeScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ["chat", "deta", "express", "firebase", "site", "typescript"],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: "master",
  },
];
